---

- hosts: all
  become: true
  tasks:

  - name: Update repository
    dnf:
      update_cache: yes

  - name: Install Apache (httpd) package
    dnf:
      name: httpd
      state: present

  - name: Enable and start Apache service
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Allow HTTP (port 80) in firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: Reload firewall to apply changes
    service:
      name: firewalld
      state: reloaded

  - name: Install PHP and PHP-FPM for Apache
    dnf:
      name: 
        - php
        - php-fpm
      state: present

  - name: Enable and start PHP-FPM service
    service:
      name: php-fpm
      enabled: yes
      state: started
